nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/order/':
            allow_origin: ['*']
            allow_headers: ['Content-Type']
            allow_methods: ['POST']
            max_age: 3600
