_application_default:
    resource: "@ApplicationDefaultBundle/Resources/config/routing.yml"

_stfalcon_portfolio:
    resource: "@StfalconPortfolioBundle/Resources/config/routing.yml"

_stfalcon_blog:
    resource: "@StfalconBlogBundle/Resources/config/routing.yml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
